### ISSUE TITLE
one_shot setting per commands group 

### ISSUE THREAD

**Issue by chrishoage** [osleg/gebaar-libinput#13]
Perhaps this is out of scope, if so please feel free to close. 

I am hoping for a `one_shot` command per `commands` group. 

This is my current config

```toml
[swipe.commands.three]
left = "xvkbd -xsendevent -text '\\[XF86Forward]'"
right = "xvkbd -xsendevent -text '\\[XF86Back]'"


[swipe.commands.four]
left = "bspc desktop -f prev.local"
right = "bspc desktop -f next.local"

[swipe.settings]
threshold = 0.50
one_shot = false
trigger_on_release = false
```

What I would like, is something like this 
```toml
[swipe.commands.three]
left = "xvkbd -xsendevent -text '\\[XF86Forward]'"
right = "xvkbd -xsendevent -text '\\[XF86Back]'"
one_shot = true

[swipe.commands.four]
left = "bspc desktop -f prev.local"
right = "bspc desktop -f next.local"

[swipe.settings]
threshold = 0.50
one_shot = false
trigger_on_release = false
```

My reasoning is that continuous swiping though workspaces is nice when there are many to scroll though to not have to preform the action multiple times. 
 
However, continuous swiping with back / forward in the browser can be disorienting and be difficult to get back to exactly where you were.
