### ISSUE TITLE
swipe.settings seemingly ignored

### ISSUE THREAD

**Issue by haarp** [osleg/gebaar-libinput#9]
Hello,

I'm currently testing gebaar, with the intent of having it replace libinput-gestures. I'm going to write an Gentoo ebuild for it later.

Right now I'm running into weird effects. My config looks like this:

```
[swipe.commands.three]
up = "xdotool key control+t"
down = "xdotool key control+w"
left = "xdotool click 8"
right = "xdotool click 9"
left_down = ""
right_down = ""
left_up = ""
right_up = ""

[swipe.commands.four]
up = ""
down = ""
left = ""
right = ""
left_down = ""
right_down = ""
left_up = ""
right_up = ""

[swipe.settings]
threshold = 5.0
one_shot = true
trigger_on_release = false

[pinch.commands]
in = ""
out = ""

[pinch.settings]
threshold = 0.25
one_shot = false
```

`swipe.commands.three` is picked up by gebaard. `swipe.settings` however appears to not be. The actual threshold is close to 0, meaning the tiniest movement with three fingers in any direction triggers the corresponding event. I've tried increasing the threshold as high as 5000 with no difference whatsoever. Similarly, toggling `one_shot` to false does not allow repeated events, nor does `trigger_on_release`=true actually trigger on release. It seems this section of the config is simply ignored.

Any ideas? Thanks!

**Comment by haarp** [comment]
It gets weirder. Not even changing the `settings.swipe.*` `value_or()` parameters in config/config.cpp and commenting them in the config instead seems to have any influence on swipe behavior whatsoever.

This is with libinput-1.14.3 on kernel 5.4.6

**Comment by osleg** [comment]
This is indeed weird, are you sure your config file is in correct location and being read by the deamon? It feels like it doesn't able to read config file.

**Comment by haarp** [comment]
> are you sure your config file is in correct location and being read by the deamon?

Yes, it is using the correct commands for the swipes, which can only come from the config.

**Comment by osleg** [comment]
Here is my config file for example 
 
```toml
[swipe.commands.three]
up = "xdotool key Control_L+F10"
down = "xdotool key Alt_L+Tab"
right = "xdotool key Alt_L+Left"
left = "xdotool key Alt_L+Right"

#[swipe.commands.four]
#up = "amixer set Master 5%+"
#down = "amixer set Master 5%-"

[pinch.commands.two]
out = "xdotool key Control_L+equal"
in = "xdotool key Control_L+minus"

[pinch.commands.rotate]
right = "xdotool key XF86AudioRaiseVolume"
left = "xdotool key XF86AudioLowerVolume"

[pinch.settings]
threshold = 0.25
one_shot = false

[swipe.settings]
threshold = 0.1
one_shot = true
trigger_on_release = false
```
